### ISSUE TITLE
TLS1.2 is not working on IBM JVMs 

### ISSUE THREAD

**Issue by brandtol** [IBMStreams/streamsx.mqtt#5]
This applies to version 1.0.0 of the toolkit. To accept TLSv1.2 we had to give the operator the jvmArg parameter

`param vmArg: "-Dcom.ibm.jsse2.overrideDefaultTLS=true";`

This should be set within the operator code, maybe in initialize()  :

`System.setProperty("com.ibm.jsse2.overrideDefaultTLS","true");`

Please close, if  this is already done in version 1.0.2 of the toolkit.

**Comment by ghost** [comment]
resolved in [release 1.0.3](https://github.com/IBMStreams/streamsx.mqtt/releases/tag/v1.0.3)
